version: '3.8'
services:
    www:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8004:80"
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - db
        networks:
            - bloodbank
    db:
        image: mysql:5.7
        restart: always
        ports:
            - "3310:3310"
        environment:
            MYSQL_ROOT_PASSWORD: gourish
            MYSQL_DATABASE: bloodbank_db
            MYSQL_USER: gourish
            MYSQL_PASSWORD: gourish
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql
        networks:
            - bloodbank
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "82:80"
        environment:
            MYSQL_ROOT_PASSWORD: gourish
            MYSQL_USER: gourish
            MYSQL_PASSWORD: gourish
            PMA_HOST: db
        networks:
            - bloodbank
        depends_on:
            - db
networks:
  bloodbank:
volumes:
  db_data:
