version: '3'
services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: bloodbank_db
            MYSQL_USER: gourish
            MYSQL_PASSWORD: Gourish@12
        volumes:
            - "./database:/docker-entrypoint-initdb.d"  # Mount the database directory for initialization
        networks:
            - lamb-docker
    php-apache-environment:
        depends_on:
            - db
        image: php:8.1.1-apache
        volumes:
            - "./:/var/www/html"
        ports:
            - 8004:80
        networks:
            - lamb-docker
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        ports:
            - '8083:80'  # Corrected port mapping
        restart: always
        environment:
            - PMA_HOST=db  # Corrected environment variable syntax
        networks:
            - lamb-docker
networks:
    lamb-docker:
        driver: bridge
