version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./bloodbank:/var/www/html
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: bloodbank_db
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
        volumes:
            - ./database:/docker-entrypoint-initdb.d  # Mount the database directory for initializatio
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8083:83'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db